import { productType } from "../types/common.types";

export const buttonLabels = [
  { slug: "like", name: "Populer" },
  { slug: "date", name: "Terbaru" },
  { slug: "harga", name: "Harga" }
];

export const galeriProdukData: productType[] = [
  {
    id: 1,
    gambar: "product-1-safiira.png",
    nama: "Bucket Lebaran",
    kategori: "Kerajinan",
    lokasi: "Lendah",
    harga: 150000,
    umkm: "Safiira Hampers",
    kecamatan: "Lendah",
    like: 3025,
    isLiked: false,
    date: new Date("2024-01-01"),
  },
  {
    id: 2,
    gambar: "product-1-safiira.png",
    nama: "Kalung Emas",
    kategori: "Aksesoris",
    lokasi: "Wates",
    harga: 200000,
    umkm: "Emas Perkasa Inc.",
    like: 230,
    isLiked: false,
    kecamatan: "Lendah",
    date: new Date("2024-01-02"),
  },
  {
    id: 3,
    gambar: "product-1-safiira.png",
    nama: "Tas Kulit",
    kategori: "Fesyen",
    lokasi: "Galur",
    harga: 300000,
    umkm: "Kulit Asli Ltd.",
    like: 345,
    isLiked: true,
    kecamatan: "Lendah",
    date: new Date("2024-01-03"),
  },
  {
    id: 4,
    gambar: "product-1-safiira.png",
    nama: "Kerajinan Tangan",
    kategori: "Kerajinan",
    lokasi: "Pengasih",
    harga: 75000,
    umkm: "Kreasi Nusantara Co.",
    like: 150,
    isLiked: false,
    kecamatan: "Lendah",
    date: new Date("2024-01-04"),
  },
  {
    id: 5,
    gambar: "product-1-safiira.png",
    nama: "Ikan Segar",
    kategori: "Perikanan",
    lokasi: "Temon",
    harga: 50000,
    umkm: "Segar Laut Fisheries",
    like: 80,
    isLiked: true,
    kecamatan: "Lendah",
    date: new Date("2024-01-05"),
  },
  {
    id: 6,
    gambar: "product-1-safiira.png",
    nama: "Pakaian Batik",
    kategori: "Fesyen",
    lokasi: "Kokap",
    harga: 250000,
    umkm: "Batik Nusantara Ltd.",
    like: 270,
    isLiked: false,
    kecamatan: "Lendah",
    date: new Date("2024-01-06"),
  },
  {
    id: 7,
    gambar: "product-1-safiira.png",
    nama: "Keripik Singkong",
    kategori: "Kuliner",
    lokasi: "Samigaluh",
    harga: 15000,
    umkm: "Camilan Asli Foods",
    like: 90,
    isLiked: true,
    kecamatan: "Lendah",
    date: new Date("2024-01-07"),
  },
  {
    id: 8,
    gambar: "product-1-safiira.png",
    nama: "Beras Organik",
    kategori: "Pertanian",
    lokasi: "Nanggulan",
    harga: 120000,
    umkm: "Tani Sejahtera Farms",
    like: 210,
    isLiked: false,
    kecamatan: "Lendah",
    date: new Date("2024-01-08"),
  },
  {
    id: 9,
    gambar: "product-1-safiira.png",
    nama: "Minyak Goreng",
    kategori: "Sembako",
    lokasi: "Sentolo",
    harga: 25000,
    umkm: "Sembako Murah Retail",
    like: 100,
    isLiked: true,
    kecamatan: "Lendah",
    date: new Date("2024-01-09"),
  },
  {
    id: 10,
    gambar: "product-1-safiira.png",
    nama: "Mesin Jahit",
    kategori: "Industri",
    lokasi: "Kalibawang",
    harga: 900000,
    umkm: "KSM Industries",
    like: 180,
    isLiked: false,
    kecamatan: "Lendah",
    date: new Date("2024-01-10"),
  },
  {
    id: 11,
    gambar: "product-1-safiira.png",
    nama: "Sabun Organik",
    kategori: "Kuliner",
    lokasi: "Temon",
    harga: 35000,
    umkm: "Natural Soap Co.",
    kecamatan: "Temon",
    like: 95,
    isLiked: true,
    date: new Date("2024-01-11"),
  },
  {
    id: 12,
    gambar: "product-1-safiira.png",
    nama: "Kerupuk Udang",
    kategori: "Kuliner",
    lokasi: "Wates",
    harga: 50000,
    umkm: "Delicious Snacks Inc.",
    kecamatan: "Wates",
    like: 60,
    isLiked: false,
    date: new Date("2024-01-12"),
  },
  {
    id: 13,
    gambar: "product-1-safiira.png",
    nama: "Sepatu Kulit",
    kategori: "Fesyen",
    lokasi: "Panjatan",
    harga: 400000,
    umkm: "Luxury Leather",
    kecamatan: "Panjatan",
    like: 220,
    isLiked: true,
    date: new Date("2024-01-13"),
  },
  {
    id: 14,
    gambar: "product-1-safiira.png",
    nama: "Jaket Denim",
    kategori: "Fesyen",
    lokasi: "Galur",
    harga: 300000,
    umkm: "Denim Style Co.",
    kecamatan: "Galur",
    like: 180,
    isLiked: false,
    date: new Date("2024-01-14"),
  },
  {
    id: 15,
    gambar: "product-1-safiira.png",
    nama: "Lukisan Kanvas",
    kategori: "Kerajinan",
    lokasi: "Lendah",
    harga: 250000,
    umkm: "Artistry Canvas",
    kecamatan: "Lendah",
    like: 110,
    isLiked: true,
    date: new Date("2024-01-15"),
  },
  {
    id: 16,
    gambar: "product-1-safiira.png",
    nama: "Madu Hutan",
    kategori: "Kuliner",
    lokasi: "Sentolo",
    harga: 120000,
    umkm: "Nature's Honey",
    kecamatan: "Sentolo",
    like: 140,
    isLiked: false,
    date: new Date("2024-01-16"),
  },
  {
    id: 17,
    gambar: "product-1-safiira.png",
    nama: "Kerajinan Kayu",
    kategori: "Kerajinan",
    lokasi: "Pengasih",
    harga: 75000,
    umkm: "Wood Craft Ltd.",
    kecamatan: "Pengasih",
    like: 95,
    isLiked: true,
    date: new Date("2024-01-17"),
  },
  {
    id: 18,
    gambar: "product-1-safiira.png",
    nama: "Batik Tulis",
    kategori: "Fesyen",
    lokasi: "Kokap",
    harga: 250000,
    umkm: "Batik Heritage",
    kecamatan: "Kokap",
    like: 270,
    isLiked: false,
    date: new Date("2024-01-18"),
  },
  {
    id: 19,
    gambar: "product-1-safiira.png",
    nama: "Keripik Tempe",
    kategori: "Kuliner",
    lokasi: "Girimulyo",
    harga: 15000,
    umkm: "Tempe Snacks",
    kecamatan: "Girimulyo",
    like: 90,
    isLiked: true,
    date: new Date("2024-01-19"),
  },
  {
    id: 20,
    gambar: "product-1-safiira.png",
    nama: "Beras Merah",
    kategori: "Pertanian",
    lokasi: "Nanggulan",
    harga: 120000,
    umkm: "Red Rice Farms",
    kecamatan: "Nanggulan",
    like: 210,
    isLiked: false,
    date: new Date("2024-01-20"),
  },
  {
    id: 21,
    gambar: "product-1-safiira.png",
    nama: "Sayur Organik",
    kategori: "Pertanian",
    lokasi: "Kalibawang",
    harga: 40000,
    umkm: "Green Veggies Co.",
    kecamatan: "Kalibawang",
    like: 190,
    isLiked: true,
    date: new Date("2024-01-21"),
  },
  {
    id: 22,
    gambar: "product-1-safiira.png",
    nama: "Minyak Atsiri",
    kategori: "Industri",
    lokasi: "Samigaluh",
    harga: 500000,
    umkm: "Essential Oils Ltd.",
    kecamatan: "Samigaluh",
    like: 75,
    isLiked: false,
    date: new Date("2024-01-22"),
  },
  {
    id: 23,
    gambar: "product-1-safiira.png",
    nama: "Jamu Tradisional",
    kategori: "Kuliner",
    lokasi: "Temon",
    harga: 50000,
    umkm: "Herbal Wellness",
    kecamatan: "Temon",
    like: 85,
    isLiked: true,
    date: new Date("2024-01-23"),
  },
  {
    id: 24,
    gambar: "product-1-safiira.png",
    nama: "Kerajinan Tembaga",
    kategori: "Kerajinan",
    lokasi: "Wates",
    harga: 150000,
    umkm: "Copper Craft Co.",
    kecamatan: "Wates",
    like: 130,
    isLiked: false,
    date: new Date("2024-01-24"),
  },
  {
    id: 25,
    gambar: "product-1-safiira.png",
    nama: "Gelang Perak",
    kategori: "Aksesoris",
    lokasi: "Panjatan",
    harga: 200000,
    umkm: "Silver Jewelry Inc.",
    kecamatan: "Panjatan",
    like: 240,
    isLiked: true,
    date: new Date("2024-01-25"),
  },
  {
    id: 26,
    gambar: "product-1-safiira.png",
    nama: "Keramik Hias",
    kategori: "Kerajinan",
    lokasi: "Galur",
    harga: 100000,
    umkm: "Ceramic Arts",
    kecamatan: "Galur",
    like: 160,
    isLiked: false,
    date: new Date("2024-01-26"),
  },
  {
    id: 27,
    gambar: "product-1-safiira.png",
    nama: "Kopi Luwak",
    kategori: "Kuliner",
    lokasi: "Lendah",
    harga: 500000,
    umkm: "Luwak Coffee Ltd.",
    kecamatan: "Lendah",
    like: 200,
    isLiked: true,
    date: new Date("2024-01-27"),
  },
  {
    id: 28,
    gambar: "product-1-safiira.png",
    nama: "Kain Tenun",
    kategori: "Fesyen",
    lokasi: "Sentolo",
    harga: 350000,
    umkm: "Weaving Traditions",
    kecamatan: "Sentolo",
    like: 180,
    isLiked: false,
    date: new Date("2024-01-28"),
  },
  {
    id: 29,
    gambar: "product-1-safiira.png",
    nama: "Mebel Kayu Jati",
    kategori: "Industri",
    lokasi: "Pengasih",
    harga: 900000,
    umkm: "Jati Furniture",
    kecamatan: "Pengasih",
    like: 290,
    isLiked: true,
    date: new Date("2024-01-29"),
  },
  {
    id: 30,
    gambar: "product-1-safiira.png",
    nama: "Ikan Hias",
    kategori: "Perikanan",
    lokasi: "Kokap",
    harga: 80000,
    umkm: "Aquatic Life",
    kecamatan: "Kokap",
    like: 140,
    isLiked: false,
    date: new Date("2024-01-30"),
  },
];