import { LatLngTuple } from "leaflet";
import { TypeData } from "./components/table/Selection";

export const EXTENDEDCOLORS = {
  primary: "#4BAF4F",
  primaryHover: "#81C784",
  secondary: "#F59C0B",
  secondaryHover: "#FBC02D",
  info: "#2194f3",
  black: "#263238",
  greyDark: "#4D4D4D",
  grey: "#717171",
  greyLight: "#89939E",
  greyBlue: "#ABBED1",
  silver: "#F5F7FA",
  white: "#FFFFFF",
  warning: "#FBC02D",
  error: "#E53835",
  success: "#2E7D31",
  accent2: "#5746AF",
  accent2a: "#EDE9FE",
  accent3: "#FA8C16",
  accent3a: "#fff2d5",
  accent4: "#52C41A",
  accent4a: "#dffbcc",
  accent5: "#F5222D",
  accent5a: "#fecaca",
  accent6: "#D9D9D9",
  primaryTint2: "#E8F5E9",
  inactive: "#BCBDBE",
};

export const EXTENDED_WINDOW = {
  sm: 640,
  md: 768,
  lg: 1024,
  xl: 1280,
  xxl: 1536,
};

interface LangType {
  label: string;
  code: string;
  link: string;
}
export const LANGUAGES: LangType[] = [
  { label: "Indonesia", code: "id", link: "/logo/indonesia.png" },
  { label: "English", code: "en", link: "/logo/uk.png" },
];

export const menuItemsData = [
  { label: "Beranda", href: "/beranda", slug: "beranda" },
  { label: "Data UMKM", href: "/data-umkm", slug: "data" },
  { label: "Statistik", href: "/statistics", slug: "statistics" },
  { label: "GIS", href: "/gis", slug: "gis" },
  { label: "Galeri Produk", href: "#", slug: "product" },
  { label: "Info Modal", href: "#", slug: "modal" },
];

export const serviceItemsData = [
  {
    title: "Datfar UMKM Sekarang",
    desc: "Daftarkan UMKM anda untuk meningkatkan promosi",
    image: "register-2.png",
    href: "/register",
  },
  {
    title: "Cari Data UMKM ",
    desc: "Dapatkan data UMKM di seluruh Kabupaten Kulon Progo",
    image: "data-search-2.png",
    href: "/data-umkm",
  },
  {
    title: "Lihat Produk",
    desc: "Tingkatkan UMKM dengan 'Bela Beli Kulon Progo' ",
    image: "shopping-2.png",
    href: "/galeri-produk",
  },
  {
    title: "Info Modal",
    desc: "Dapat info modal untuk membantu peningkatan UMKM Anda ",
    image: "modal-vector.png",
    href: "/info-modal",
  },
];

export const socialMediaData = [
  { path: "/logo/ig.svg", url: "#" },
  { path: "/logo/twt.svg", url: "#" },
  { path: "/logo/web.svg", url: "#" },
  { path: "/logo/yt.svg", url: "#" },
];

export const FaqsData = [
  {
    title: "Apa itu e-UMKM Kulon Progo?",
    content:
      "LearnNow is a platform where you can find a variety of online and offline courses suitable for learners of all levels.",
  },
  {
    title: "Apakah ini situs resmi pemerintah Kulon Progo?",
    content:
      "LearnNow is a user-friendly platform designed to help individuals in discovering courses that align with their interests and goals. Simply browse through the available courses and enroll in those that you find interesting.",
  },
  {
    title: "Bagaiamana cara mendaftarkan UMKM baru?",
    content:
      "To list your courses on LearnNow, you can fill out a submission form on our website or contact us via email at info@email.com.",
  },
  {
    title: "Apakah saya bisa menjual produk saya di situs ini?",
    content:
      "LearnNow serves as a platform for course discovery and does not take responsibility for the quality or content of the courses listed. Users are advised to conduct their own research before enrolling.",
  },
];
export interface titleSlugType {
  title: string;
  slug: string;
}

export interface colorType {
  text: string;
  bg: string;
}

export const dataColumnUMKMBuilder: titleSlugType[] = [
  {
    title: "ID",
    slug: "index",
  },
  {
    title: "Nama UMKM",
    slug: "name",
  },
  {
    title: "Skala Usaha",
    slug: "skala",
  },
  {
    title: "Bidang",
    slug: "bidang",
  },
  {
    title: "Badan Hukum",
    slug: "badanHukum",
  },
  {
    title: "Pengampu",
    slug: "pengampu",
  },
  {
    title: "Alamat",
    slug: "alamat",
  },
];

export interface nameSlugType {
  name: string;
  slug: string;
}

export const skalaUsaha = [
  {
    name: "Usaha Mikro",
    slug: "mikro",
  },
  {
    name: "Usaha Kecil",
    slug: "kecil",
  },
  {
    name: "Usaha Menengah",
    slug: "menengah",
  },
];

export const badanHukumUsaha: TypeData[] = [
  {
    name: "PT",
    slug: "pt",
  },
  {
    name: "CV",
    slug: "cv",
  },
  {
    name: "Firma",
    slug: "firma",
  },
  {
    name: "Perseorangan",
    slug: "perseorangan",
  },
];

export const dinasPengampu = [
  {
    name: "Dinas PMD Dalduk",
    slug: "dalduk",
  },
  {
    name: "Dinas Sosial",
    slug: "sosial",
  },
  {
    name: "Dinas Kelautan dan Perikanan",
    slug: "perikanan",
  },
  {
    name: "Dinas Perhubungan",
    slug: "perhubungan",
  },
  {
    name: "Dinas Pariwisata",
    slug: "pariwisata",
  },
  {
    name: "Dinas Lingkungan Hidup",
    slug: "lingkungan",
  },
  {
    name: "Dinas Koperasi dan UKM",
    slug: "koperasi_ukm",
  },
  {
    name: "Dinas Pertanian dan Pangan",
    slug: "pertanian_pangan",
  },
  {
    name: "Dinas Perdagangan dan Perindustrian",
    slug: "perdangan",
  },
];

export const bidangUsaha = [
  {
    name: "Pertanian",
    slug: "pertanian",
  },
  {
    name: "Perikanan",
    slug: "perikanan",
  },
  {
    name: "Perdagangan",
    slug: "perdagangan",
  },
  {
    name: "Industri Manufaktur",
    slug: "industri-manufaktur",
  },
  {
    name: "Konstruksi",
    slug: "konstruksi",
  },
  {
    name: "Transportasi dan Logistik",
    slug: "transportasi-logistik",
  },
  {
    name: "Teknologi Informasi",
    slug: "teknologi-informasi",
  },
  {
    name: "Jasa Keuangan",
    slug: "jasa-keuangan",
  },
  {
    name: "Kesehatan",
    slug: "kesehatan",
  },
  {
    name: "Pendidikan",
    slug: "pendidikan",
  },
  {
    name: "Pariwisata",
    slug: "pariwisata",
  },
  {
    name: "Energi dan Sumber Daya Mineral",
    slug: "energi-sumber-daya-mineral",
  },
  {
    name: "Properti dan Real Estat",
    slug: "properti-real-estat",
  },
  {
    name: "Pertambangan",
    slug: "pertambangan",
  },
  {
    name: "Hukum dan Konsultasi",
    slug: "hukum-konsultasi",
  },
];

export const kecamatanKulonProgo = [
  "Temon",
  "Wates",
  "Panjatan",
  "Galur",
  "Lendah",
  "Sentolo",
  "Pengasih",
  "Kokap",
  "Girimulyo",
  "Nanggulan",
  "Kalibawang",
  "Samigaluh",
];

export interface UMKMProperties {
  index: number;
  avatar: string;
  name: string;
  skala: string;
  bidang: string;
  badanHukum: string;
  pengampu: string;
  noTelp: string;
  kecamatan: string;
  alamat: string;
  position?: LatLngTuple;
  [key: string]: any;
}

export const umkmData: UMKMProperties[] = [
  {
    index: 1,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Kopi Starprog",
    skala: "Usaha Menengah",
    bidang: "Industri Manufaktur",
    badanHukum: "CV",
    pengampu: "Dinas Koperasi dan UKM",
    noTelp: "086868130401",
    kecamatan: "Lendah",
    alamat: "RT 10 RW 00, Gentan, Sidorejo, Lendah",
    position: [-7.91239, 110.22927] as LatLngTuple,
  },
  {
    index: 2,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Tigan Jaya",
    skala: "Usaha Kecil",
    badanHukum: "Perseorangan",
    bidang: "Industri Manufaktur",
    pengampu: "Dinas Sosial",
    noTelp: "086868130401",
    kecamatan: "Lendah",
    alamat: "RT 12 RW 00, Pulo, Gulurejo, Lendah",
    position: [-7.900172, 110.207867] as LatLngTuple,
  },
  {
    index: 3,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Kangenanku",
    skala: "Usaha Mikro",
    badanHukum: "PT",
    bidang: "Industri Manufaktur",
    pengampu: "Dinas Koperasi dan UKM",
    noTelp: "086868130401",
    kecamatan: "Lendah",
    alamat: "RT 05 RW 01, Banaran, Jatirejo, Lendah",
    position: [-7.903232, 110.203919] as LatLngTuple,
  },
  {
    index: 4,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Sari Bumi",
    skala: "Usaha Kecil",
    badanHukum: "Firma",
    bidang: "Pertanian",
    pengampu: "Dinas Pertanian dan Pangan",
    noTelp: "086868130402",
    kecamatan: "Nanggulan",
    alamat: "RT 01 RW 02, Sidoarum, Nanggulan",
    position: [-7.7861, 110.1748] as LatLngTuple,
  },
  {
    index: 5,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Laut Segar",
    skala: "Usaha Menengah",
    badanHukum: "Firma",
    bidang: "Perikanan",
    pengampu: "Dinas Kelautan dan Perikanan",
    noTelp: "086868130403",
    kecamatan: "Samigaluh",
    alamat: "RT 02 RW 03, Samiran, Samigaluh",
    position: [-7.6934, 110.17] as LatLngTuple, // Samigaluh
  },
  {
    index: 6,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Transport Maju",
    skala: "Usaha Mikro",
    badanHukum: "Perseorangan",
    bidang: "Transportasi dan Logistik",
    pengampu: "Dinas Perhubungan",
    noTelp: "086868130404",
    kecamatan: "Sentolo",
    alamat: "RT 03 RW 04, Senayan, Sentolo",
  },
  {
    index: 7,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Pariwisata Indah",
    skala: "Usaha Menengah",
    badanHukum: "PT",
    bidang: "Pariwisata",
    pengampu: "Dinas Pariwisata",
    noTelp: "086868130405",
    kecamatan: "Wates",
    alamat: "RT 04 RW 05, Wetan, Wates",
    position: [-7.911981, 110.096718],
  },
  {
    index: 8,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Energi Surya",
    skala: "Usaha Kecil",
    badanHukum: "Firma",
    bidang: "Energi dan Sumber Daya Mineral",
    pengampu: "Dinas Lingkungan Hidup",
    noTelp: "086868130406",
    kecamatan: "Galur",
    alamat: "RT 05 RW 06, Galur Selatan, Galur",
  },
  {
    index: 9,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Kopi Sejahtera",
    skala: "Usaha Mikro",
    badanHukum: "Perseorangan",
    bidang: "Industri Manufaktur",
    pengampu: "Dinas Perdagangan dan Perindustrian",
    noTelp: "086868130407",
    kecamatan: "Pengasih",
    alamat: "RT 06 RW 07, Pengasih Utara, Pengasih",
  },
  {
    index: 10,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Jasa Keuangan Aman",
    skala: "Usaha Menengah",
    badanHukum: "CV",
    bidang: "Jasa Keuangan",
    pengampu: "Dinas Sosial",
    noTelp: "086868130408",
    kecamatan: "Temon",
    alamat: "RT 07 RW 08, Temon Barat, Temon",
  },
  {
    index: 11,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Pendidikan Ceria",
    skala: "Usaha Kecil",
    badanHukum: "Firma",
    bidang: "Pendidikan",
    pengampu: "Dinas Koperasi dan UKM",
    noTelp: "086868130409",
    kecamatan: "Lendah",
    alamat: "RT 08 RW 09, Gentan, Sidorejo, Lendah",
    position: [-7.904763, 110.193105],
  },
  {
    index: 12,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Kesehatan Prima",
    skala: "Usaha Mikro",
    badanHukum: "Perseorangan",
    bidang: "Kesehatan",
    pengampu: "Dinas Pariwisata",
    noTelp: "086868130410",
    kecamatan: "Nanggulan",
    alamat: "RT 09 RW 10, Sidoarum, Nanggulan",
  },
  {
    index: 13,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Properti Utama",
    skala: "Usaha Menengah",
    badanHukum: "PT",
    bidang: "Properti dan Real Estat",
    pengampu: "Dinas Perhubungan",
    noTelp: "086868130411",
    kecamatan: "Samigaluh",
    alamat: "RT 10 RW 11, Samiran, Samigaluh",
  },
  {
    index: 14,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Perikanan Sejahtera",
    skala: "Usaha Kecil",
    badanHukum: "Firma",
    bidang: "Perikanan",
    pengampu: "Dinas Kelautan dan Perikanan",
    noTelp: "086868130412",
    kecamatan: "Sentolo",
    alamat: "RT 11 RW 12, Senayan, Sentolo",
  },
  {
    index: 15,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Teknologi Masa Depan",
    skala: "Usaha Mikro",
    badanHukum: "Perseorangan",
    bidang: "Teknologi Informasi",
    pengampu: "Dinas Perdagangan dan Perindustrian",
    noTelp: "086868130413",
    kecamatan: "Wates",
    alamat: "RT 12 RW 13, Wetan, Wates",
    position: [-7.911216, 110.109075],
  },
  {
    index: 16,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Pertanian Maju",
    skala: "Usaha Menengah",
    badanHukum: "Firma",
    bidang: "Pertanian",
    pengampu: "Dinas Pertanian dan Pangan",
    noTelp: "086868130414",
    kecamatan: "Galur",
    alamat: "RT 13 RW 14, Galur Selatan, Galur",
  },
  {
    index: 17,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Hukum dan Konsultasi Jaya",
    skala: "Usaha Kecil",
    badanHukum: "Firma",
    bidang: "Hukum dan Konsultasi",
    pengampu: "Dinas PMD Dalduk",
    noTelp: "086868130415",
    kecamatan: "Pengasih",
    alamat: "RT 14 RW 15, Pengasih Utara, Pengasih",
  },
  {
    index: 18,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Pertambangan Sejahtera",
    skala: "Usaha Mikro",
    badanHukum: "PT",
    bidang: "Pertambangan",
    pengampu: "Dinas Lingkungan Hidup",
    noTelp: "086868130416",
    kecamatan: "Sentolo",
    alamat: "RT 15 RW 16, Senayan, Sentolo",
  },
  {
    index: 19,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Teknologi Cerdas",
    skala: "Usaha Menengah",
    badanHukum: "CV",
    bidang: "Teknologi Informasi",
    pengampu: "Dinas Perdagangan dan Perindustrian",
    noTelp: "086868130417",
    kecamatan: "Wates",
    alamat: "RT 16 RW 17, Wetan, Wates",
    position: [-7.908046, 110.125294],
  },
  {
    index: 20,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Jasa Kesehatan",
    skala: "Usaha Kecil",
    badanHukum: "Perseorangan",
    bidang: "Kesehatan",
    pengampu: "Dinas Sosial",
    noTelp: "086868130418",
    kecamatan: "Nanggulan",
    alamat: "RT 17 RW 18, Sidoarum, Nanggulan",
  },
  {
    index: 21,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Energi Hijau",
    skala: "Usaha Mikro",
    badanHukum: "Firma",
    bidang: "Energi dan Sumber Daya Mineral",
    pengampu: "Dinas Pariwisata",
    noTelp: "086868130419",
    kecamatan: "Samigaluh",
    alamat: "RT 18 RW 19, Samiran, Samigaluh",
  },
  {
    index: 22,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Transportasi Sejahtera",
    skala: "Usaha Menengah",
    badanHukum: "Firma",
    bidang: "Transportasi dan Logistik",
    pengampu: "Dinas Perhubungan",
    noTelp: "086868130420",
    kecamatan: "Sentolo",
    alamat: "RT 19 RW 20, Senayan, Sentolo",
  },
  {
    index: 23,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Industri Kreatif",
    skala: "Usaha Kecil",
    badanHukum: "PT",
    bidang: "Industri Manufaktur",
    pengampu: "Dinas Perdagangan dan Perindustrian",
    noTelp: "086868130421",
    kecamatan: "Wates",
    alamat: "RT 20 RW 21, Wetan, Wates",
    position: [-7.906516, 110.136217],
  },
  {
    index: 24,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Jasa Keuangan Stabil",
    skala: "Usaha Mikro",
    badanHukum: "Perseorangan",
    bidang: "Jasa Keuangan",
    pengampu: "Dinas Sosial",
    noTelp: "086868130422",
    kecamatan: "Galur",
    alamat: "RT 21 RW 22, Galur Selatan, Galur",
  },
  {
    index: 25,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Teknologi dan Pendidikan",
    skala: "Usaha Menengah",
    badanHukum: "Firma",
    bidang: "Pendidikan",
    pengampu: "Dinas Koperasi dan UKM",
    noTelp: "086868130423",
    kecamatan: "Pengasih",
    alamat: "RT 22 RW 23, Pengasih Utara, Pengasih",
  },
  {
    index: 26,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Konstruksi Mandiri",
    skala: "Usaha Kecil",
    badanHukum: "Perseorangan",
    bidang: "Konstruksi",
    pengampu: "Dinas Pariwisata",
    noTelp: "086868130424",
    kecamatan: "Nanggulan",
    alamat: "RT 23 RW 24, Sidoarum, Nanggulan",
  },
  {
    index: 27,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Perdagangan Tani",
    skala: "Usaha Mikro",
    badanHukum: "Firma",
    bidang: "Perdagangan",
    pengampu: "Dinas Pertanian dan Pangan",
    noTelp: "086868130425",
    kecamatan: "Samigaluh",
    alamat: "RT 24 RW 25, Samiran, Samigaluh",
  },
  {
    index: 28,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Jasa Logistik Cepat",
    skala: "Usaha Menengah",
    badanHukum: "PT",
    bidang: "Transportasi dan Logistik",
    pengampu: "Dinas Perhubungan",
    noTelp: "086868130426",
    kecamatan: "Sentolo",
    alamat: "RT 25 RW 26, Senayan, Sentolo",
  },
  {
    index: 29,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Hukum dan Bisnis",
    skala: "Usaha Kecil",
    badanHukum: "Firma",
    bidang: "Hukum dan Konsultasi",
    pengampu: "Dinas PMD Dalduk",
    noTelp: "086868130427",
    kecamatan: "Wates",
    alamat: "RT 26 RW 27, Wetan, Wates",
    position: [-7.899304, 110.139527],
  },
  {
    index: 30,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Teknologi Inovatif",
    skala: "Usaha Mikro",
    badanHukum: "Perseorangan",
    bidang: "Teknologi Informasi",
    pengampu: "Dinas Perdagangan dan Perindustrian",
    noTelp: "086868130428",
    kecamatan: "Galur",
    alamat: "RT 27 RW 28, Galur Selatan, Galur",
  },
  {
    index: 31,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Tani Sukses",
    skala: "Usaha Menengah",
    badanHukum: "CV",
    bidang: "Pertanian",
    pengampu: "Dinas Pertanian dan Pangan",
    noTelp: "086868130429",
    kecamatan: "Temon",
    alamat: "RT 28 RW 29, Temon Timur, Temon",
  },
  {
    index: 32,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Pangan Sehat",
    skala: "Usaha Kecil",
    badanHukum: "Firma",
    bidang: "Perdagangan",
    pengampu: "Dinas Perdagangan dan Perindustrian",
    noTelp: "086868130430",
    kecamatan: "Wates",
    alamat: "RT 29 RW 30, Wetan, Wates",
    position: [-7.894932, 110.142837],
  },
  {
    index: 33,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Jasa Angkut",
    skala: "Usaha Mikro",
    badanHukum: "Firma",
    bidang: "Transportasi dan Logistik",
    pengampu: "Dinas Perhubungan",
    noTelp: "086868130431",
    kecamatan: "Sentolo",
    alamat: "RT 30 RW 31, Senayan, Sentolo",
  },
  {
    index: 34,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Konsultasi Bisnis",
    skala: "Usaha Menengah",
    badanHukum: "PT",
    bidang: "Hukum dan Konsultasi",
    pengampu: "Dinas PMD Dalduk",
    noTelp: "086868130432",
    kecamatan: "Pengasih",
    alamat: "RT 31 RW 32, Pengasih Selatan, Pengasih",
  },
  {
    index: 35,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Industri Maju",
    skala: "Usaha Kecil",
    badanHukum: "Perseorangan",
    bidang: "Industri Manufaktur",
    pengampu: "Dinas Koperasi dan UKM",
    noTelp: "086868130433",
    kecamatan: "Lendah",
    alamat: "RT 32 RW 33, Gentan, Sidorejo, Lendah",
    position: [-7.922275, 110.201001],
  },
  {
    index: 36,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Usaha Bersama",
    skala: "Usaha Mikro",
    badanHukum: "Perseorangan",
    bidang: "Konstruksi",
    pengampu: "Dinas Lingkungan Hidup",
    noTelp: "086868130434",
    kecamatan: "Nanggulan",
    alamat: "RT 33 RW 34, Sidoarum, Nanggulan",
  },
  {
    index: 37,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Pangan Mandiri",
    skala: "Usaha Menengah",
    badanHukum: "CV",
    bidang: "Pertanian",
    pengampu: "Dinas Pertanian dan Pangan",
    noTelp: "086868130435",
    kecamatan: "Samigaluh",
    alamat: "RT 34 RW 35, Samiran, Samigaluh",
  },
  {
    index: 38,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Perikanan Maju",
    skala: "Usaha Kecil",
    badanHukum: "Firma",
    bidang: "Perikanan",
    pengampu: "Dinas Kelautan dan Perikanan",
    noTelp: "086868130436",
    kecamatan: "Temon",
    alamat: "RT 35 RW 36, Temon Barat, Temon",
  },
  {
    index: 39,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Teknologi Terkini",
    skala: "Usaha Mikro",
    badanHukum: "Firma",
    bidang: "Teknologi Informasi",
    pengampu: "Dinas Perdagangan dan Perindustrian",
    noTelp: "086868130437",
    kecamatan: "Wates",
    alamat: "RT 36 RW 37, Wetan, Wates",
    position: [-7.897992, 110.119005],
  },
  {
    index: 40,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Jasa Keuangan Makmur",
    skala: "Usaha Menengah",
    badanHukum: "PT",
    bidang: "Jasa Keuangan",
    pengampu: "Dinas Sosial",
    noTelp: "086868130438",
    kecamatan: "Galur",
    alamat: "RT 37 RW 38, Galur Utara, Galur",
  },
  {
    index: 41,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Teknologi dan Informasi",
    skala: "Usaha Kecil",
    badanHukum: "Perseorangan",
    bidang: "Teknologi Informasi",
    pengampu: "Dinas Perdagangan dan Perindustrian",
    noTelp: "086868130439",
    kecamatan: "Pengasih",
    alamat: "RT 38 RW 39, Pengasih Timur, Pengasih",
  },
  {
    index: 42,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Konstruksi Jaya",
    skala: "Usaha Mikro",
    badanHukum: "Firma",
    bidang: "Konstruksi",
    pengampu: "Dinas Lingkungan Hidup",
    noTelp: "086868130440",
    kecamatan: "Nanggulan",
    alamat: "RT 39 RW 40, Sidoarum, Nanggulan",
  },
  {
    index: 43,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Pangan Lestari",
    skala: "Usaha Menengah",
    badanHukum: "CV",
    bidang: "Pertanian",
    pengampu: "Dinas Pertanian dan Pangan",
    noTelp: "086868130441",
    kecamatan: "Samigaluh",
    alamat: "RT 40 RW 41, Samiran, Samigaluh",
  },
  {
    index: 44,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Hasil Laut Sejahtera",
    skala: "Usaha Kecil",
    badanHukum: "Firma",
    bidang: "Perikanan",
    pengampu: "Dinas Kelautan dan Perikanan",
    noTelp: "086868130442",
    kecamatan: "Temon",
    alamat: "RT 41 RW 42, Temon Timur, Temon",
  },
  {
    index: 45,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Inovasi Teknologi",
    skala: "Usaha Mikro",
    badanHukum: "Firma",
    bidang: "Teknologi Informasi",
    pengampu: "Dinas Perdagangan dan Perindustrian",
    noTelp: "086868130443",
    kecamatan: "Wates",
    alamat: "RT 42 RW 43, Wetan, Wates",
    position: [-7.891326, 110.118564],
  },
  {
    index: 46,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Keuangan Sejahtera",
    skala: "Usaha Menengah",
    badanHukum: "PT",
    bidang: "Jasa Keuangan",
    pengampu: "Dinas Sosial",
    noTelp: "086868130444",
    kecamatan: "Galur",
    alamat: "RT 43 RW 44, Galur Selatan, Galur",
  },
  {
    index: 47,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Informasi Masa Depan",
    skala: "Usaha Kecil",
    badanHukum: "Perseorangan",
    bidang: "Teknologi Informasi",
    pengampu: "Dinas Perdagangan dan Perindustrian",
    noTelp: "086868130445",
    kecamatan: "Pengasih",
    alamat: "RT 44 RW 45, Pengasih Barat, Pengasih",
  },
  {
    index: 48,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Bangun Bersama",
    skala: "Usaha Mikro",
    badanHukum: "Firma",
    bidang: "Konstruksi",
    pengampu: "Dinas Lingkungan Hidup",
    noTelp: "086868130446",
    kecamatan: "Nanggulan",
    alamat: "RT 45 RW 46, Sidoarum, Nanggulan",
  },
  {
    index: 49,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Pertanian Mandiri",
    skala: "Usaha Menengah",
    badanHukum: "CV",
    bidang: "Pertanian",
    pengampu: "Dinas Pertanian dan Pangan",
    noTelp: "086868130447",
    kecamatan: "Samigaluh",
    alamat: "RT 46 RW 47, Samiran, Samigaluh",
  },
  {
    index: 50,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Lautan Lestari",
    skala: "Usaha Kecil",
    badanHukum: "Firma",
    bidang: "Perikanan",
    pengampu: "Dinas Kelautan dan Perikanan",
    noTelp: "086868130448",
    kecamatan: "Temon",
    alamat: "RT 47 RW 48, Temon Barat, Temon",
  },
  {
    index: 51,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Energi Hijau",
    skala: "Usaha Menengah",
    badanHukum: "PT",
    bidang: "Energi dan Sumber Daya Mineral",
    pengampu: "Dinas Perdagangan dan Perindustrian",
    noTelp: "086868130451",
    kecamatan: "Galur",
    alamat: "RT 48 RW 49, Galur Timur, Galur",
  },
  {
    index: 52,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Properti Maju",
    skala: "Usaha Kecil",
    badanHukum: "Firma",
    bidang: "Properti dan Real Estat",
    pengampu: "Dinas Pariwisata",
    noTelp: "086868130452",
    kecamatan: "Temon",
    alamat: "RT 49 RW 50, Temon Timur, Temon",
  },
  {
    index: 53,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Konsultasi Hukum",
    skala: "Usaha Mikro",
    badanHukum: "Perseorangan",
    bidang: "Hukum dan Konsultasi",
    pengampu: "Dinas PMD Dalduk",
    noTelp: "086868130453",
    kecamatan: "Wates",
    alamat: "RT 50 RW 51, Wetan, Wates",
    position: [-7.892528, 110.123418],
  },
  {
    index: 54,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Tambang Sejahtera",
    skala: "Usaha Menengah",
    badanHukum: "CV",
    bidang: "Pertambangan",
    pengampu: "Dinas Lingkungan Hidup",
    noTelp: "086868130454",
    kecamatan: "Sentolo",
    alamat: "RT 51 RW 52, Senayan, Sentolo",
  },
  {
    index: 55,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Laut Bersih",
    skala: "Usaha Kecil",
    badanHukum: "Firma",
    bidang: "Perikanan",
    pengampu: "Dinas Kelautan dan Perikanan",
    noTelp: "086868130455",
    kecamatan: "Pengasih",
    alamat: "RT 52 RW 53, Pengasih Utara, Pengasih",
  },
  {
    index: 56,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Pariwisata Nusantara",
    skala: "Usaha Mikro",
    badanHukum: "Perseorangan",
    bidang: "Pariwisata",
    pengampu: "Dinas Pariwisata",
    noTelp: "086868130456",
    kecamatan: "Nanggulan",
    alamat: "RT 53 RW 54, Sidoarum, Nanggulan",
  },
  {
    index: 57,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Industri Sejahtera",
    skala: "Usaha Menengah",
    badanHukum: "PT",
    bidang: "Industri Manufaktur",
    pengampu: "Dinas Koperasi dan UKM",
    noTelp: "086868130457",
    kecamatan: "Samigaluh",
    alamat: "RT 54 RW 55, Samiran, Samigaluh",
  },
  {
    index: 58,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Pendidikan Cerdas",
    skala: "Usaha Kecil",
    badanHukum: "Firma",
    bidang: "Pendidikan",
    pengampu: "Dinas Sosial",
    noTelp: "086868130458",
    kecamatan: "Temon",
    alamat: "RT 55 RW 56, Temon Timur, Temon",
  },
  {
    index: 59,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Kesehatan Mandiri",
    skala: "Usaha Mikro",
    badanHukum: "Perseorangan",
    bidang: "Kesehatan",
    pengampu: "Dinas Sosial",
    noTelp: "086868130459",
    kecamatan: "Wates",
    alamat: "RT 56 RW 57, Wetan, Wates",
    position: [-7.887063, 110.129376],
  },
  {
    index: 60,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Transportasi Cepat",
    skala: "Usaha Menengah",
    badanHukum: "CV",
    bidang: "Transportasi dan Logistik",
    pengampu: "Dinas Perhubungan",
    noTelp: "086868130460",
    kecamatan: "Sentolo",
    alamat: "RT 57 RW 58, Senayan, Sentolo",
  },
  {
    index: 61,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Pertanian Maju",
    skala: "Usaha Kecil",
    badanHukum: "Firma",
    bidang: "Pertanian",
    pengampu: "Dinas Pertanian dan Pangan",
    noTelp: "086868130461",
    kecamatan: "Pengasih",
    alamat: "RT 58 RW 59, Pengasih Timur, Pengasih",
  },
  {
    index: 62,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Hukum Aman",
    skala: "Usaha Mikro",
    badanHukum: "Perseorangan",
    bidang: "Hukum dan Konsultasi",
    pengampu: "Dinas PMD Dalduk",
    noTelp: "086868130462",
    kecamatan: "Nanggulan",
    alamat: "RT 59 RW 60, Sidoarum, Nanggulan",
  },
  {
    index: 63,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Properti Jaya",
    skala: "Usaha Menengah",
    badanHukum: "PT",
    bidang: "Properti dan Real Estat",
    pengampu: "Dinas Pariwisata",
    noTelp: "086868130463",
    kecamatan: "Samigaluh",
    alamat: "RT 60 RW 61, Samiran, Samigaluh",
  },
  {
    index: 64,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Konsultasi Terpercaya",
    skala: "Usaha Kecil",
    badanHukum: "Firma",
    bidang: "Hukum dan Konsultasi",
    pengampu: "Dinas PMD Dalduk",
    noTelp: "086868130464",
    kecamatan: "Temon",
    alamat: "RT 61 RW 62, Temon Barat, Temon",
  },
  {
    index: 65,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Tambang Aman",
    skala: "Usaha Mikro",
    badanHukum: "Perseorangan",
    bidang: "Pertambangan",
    pengampu: "Dinas Lingkungan Hidup",
    noTelp: "086868130465",
    kecamatan: "Wates",
    alamat: "RT 62 RW 63, Wetan, Wates",
    position: [-7.879194, 110.131252],
  },
  {
    index: 66,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Laut Lestari",
    skala: "Usaha Menengah",
    badanHukum: "CV",
    bidang: "Perikanan",
    pengampu: "Dinas Kelautan dan Perikanan",
    noTelp: "086868130466",
    kecamatan: "Sentolo",
    alamat: "RT 63 RW 64, Senayan, Sentolo",
  },
  {
    index: 67,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Pariwisata Bahari",
    skala: "Usaha Kecil",
    badanHukum: "Firma",
    bidang: "Pariwisata",
    pengampu: "Dinas Pariwisata",
    noTelp: "086868130467",
    kecamatan: "Pengasih",
    alamat: "RT 64 RW 65, Pengasih Utara, Pengasih",
  },
  {
    index: 68,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Industri Kreatif",
    skala: "Usaha Mikro",
    badanHukum: "Perseorangan",
    bidang: "Industri Manufaktur",
    pengampu: "Dinas Koperasi dan UKM",
    noTelp: "086868130468",
    kecamatan: "Nanggulan",
    alamat: "RT 65 RW 66, Sidoarum, Nanggulan",
  },
  {
    index: 69,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Pendidikan Terdepan",
    skala: "Usaha Menengah",
    badanHukum: "PT",
    bidang: "Pendidikan",
    pengampu: "Dinas Sosial",
    noTelp: "086868130469",
    kecamatan: "Samigaluh",
    alamat: "RT 66 RW 67, Samiran, Samigaluh",
  },
  {
    index: 70,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Kesehatan Sejahtera",
    skala: "Usaha Kecil",
    badanHukum: "Firma",
    bidang: "Kesehatan",
    pengampu: "Dinas Sosial",
    noTelp: "086868130470",
    kecamatan: "Temon",
    alamat: "RT 67 RW 68, Temon Timur, Temon",
  },
  {
    index: 71,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Transportasi Aman",
    skala: "Usaha Mikro",
    badanHukum: "Perseorangan",
    bidang: "Transportasi dan Logistik",
    pengampu: "Dinas Perhubungan",
    noTelp: "086868130471",
    kecamatan: "Wates",
    alamat: "RT 68 RW 69, Wetan, Wates",
    position: [-7.886028, 110.134861],
  },
  {
    index: 72,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Pertanian Berkah",
    skala: "Usaha Menengah",
    badanHukum: "CV",
    bidang: "Pertanian",
    pengampu: "Dinas Pertanian dan Pangan",
    noTelp: "086868130472",
    kecamatan: "Sentolo",
    alamat: "RT 69 RW 70, Senayan, Sentolo",
  },
  {
    index: 73,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Hukum Terdepan",
    skala: "Usaha Kecil",
    badanHukum: "Firma",
    bidang: "Hukum dan Konsultasi",
    pengampu: "Dinas PMD Dalduk",
    noTelp: "086868130473",
    kecamatan: "Pengasih",
    alamat: "RT 70 RW 71, Pengasih Timur, Pengasih",
  },
  {
    index: 74,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Properti Lestari",
    skala: "Usaha Mikro",
    badanHukum: "Perseorangan",
    bidang: "Properti dan Real Estat",
    pengampu: "Dinas Pariwisata",
    noTelp: "086868130474",
    kecamatan: "Nanggulan",
    alamat: "RT 71 RW 72, Sidoarum, Nanggulan",
  },
  {
    index: 75,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Konsultasi Cepat",
    skala: "Usaha Menengah",
    badanHukum: "PT",
    bidang: "Hukum dan Konsultasi",
    pengampu: "Dinas PMD Dalduk",
    noTelp: "086868130475",
    kecamatan: "Samigaluh",
    alamat: "RT 72 RW 73, Samiran, Samigaluh",
  },
  {
    index: 76,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Tambang Jaya",
    skala: "Usaha Kecil",
    badanHukum: "Firma",
    bidang: "Pertambangan",
    pengampu: "Dinas Lingkungan Hidup",
    noTelp: "086868130476",
    kecamatan: "Temon",
    alamat: "RT 73 RW 74, Temon Barat, Temon",
  },
  {
    index: 77,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Laut Sejahtera",
    skala: "Usaha Mikro",
    badanHukum: "Perseorangan",
    bidang: "Perikanan",
    pengampu: "Dinas Kelautan dan Perikanan",
    noTelp: "086868130477",
    kecamatan: "Wates",
    alamat: "RT 74 RW 75, Wetan, Wates",
    position: [-7.887698, 110.129417],
  },
  {
    index: 78,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Pariwisata Indah",
    skala: "Usaha Menengah",
    badanHukum: "CV",
    bidang: "Pariwisata",
    pengampu: "Dinas Pariwisata",
    noTelp: "086868130478",
    kecamatan: "Sentolo",
    alamat: "RT 75 RW 76, Senayan, Sentolo",
  },
  {
    index: 79,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Industri Maju",
    skala: "Usaha Kecil",
    badanHukum: "Firma",
    bidang: "Industri Manufaktur",
    pengampu: "Dinas Koperasi dan UKM",
    noTelp: "086868130479",
    kecamatan: "Pengasih",
    alamat: "RT 76 RW 77, Pengasih Utara, Pengasih",
  },
  {
    index: 80,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Pendidikan Sejahtera",
    skala: "Usaha Mikro",
    badanHukum: "Perseorangan",
    bidang: "Pendidikan",
    pengampu: "Dinas Sosial",
    noTelp: "086868130480",
    kecamatan: "Nanggulan",
    alamat: "RT 77 RW 78, Sidoarum, Nanggulan",
  },
  {
    index: 81,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Kesehatan Aman",
    skala: "Usaha Menengah",
    badanHukum: "PT",
    bidang: "Kesehatan",
    pengampu: "Dinas Sosial",
    noTelp: "086868130481",
    kecamatan: "Samigaluh",
    alamat: "RT 78 RW 79, Samiran, Samigaluh",
  },
  {
    index: 82,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Transportasi Lestari",
    skala: "Usaha Kecil",
    badanHukum: "Firma",
    bidang: "Transportasi dan Logistik",
    pengampu: "Dinas Perhubungan",
    noTelp: "086868130482",
    kecamatan: "Temon",
    alamat: "RT 79 RW 80, Temon Timur, Temon",
  },
  {
    index: 83,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Pertanian Sejahtera",
    skala: "Usaha Mikro",
    badanHukum: "Perseorangan",
    bidang: "Pertanian",
    pengampu: "Dinas Pertanian dan Pangan",
    noTelp: "086868130483",
    kecamatan: "Wates",
    alamat: "RT 80 RW 81, Wetan, Wates",
    position: [-7.884467, 110.143665],
  },
  {
    index: 84,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Hukum Lestari",
    skala: "Usaha Menengah",
    badanHukum: "CV",
    bidang: "Hukum dan Konsultasi",
    pengampu: "Dinas PMD Dalduk",
    noTelp: "086868130484",
    kecamatan: "Sentolo",
    alamat: "RT 81 RW 82, Senayan, Sentolo",
  },
  {
    index: 85,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Properti Berkah",
    skala: "Usaha Kecil",
    badanHukum: "Firma",
    bidang: "Properti dan Real Estat",
    pengampu: "Dinas Pariwisata",
    noTelp: "086868130485",
    kecamatan: "Pengasih",
    alamat: "RT 82 RW 83, Pengasih Timur, Pengasih",
  },
  {
    index: 86,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Konsultasi Cepat",
    skala: "Usaha Mikro",
    badanHukum: "Perseorangan",
    bidang: "Hukum dan Konsultasi",
    pengampu: "Dinas PMD Dalduk",
    noTelp: "086868130486",
    kecamatan: "Nanggulan",
    alamat: "RT 83 RW 84, Sidoarum, Nanggulan",
  },
  {
    index: 87,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Pariwisata Terdepan",
    skala: "Usaha Menengah",
    badanHukum: "PT",
    bidang: "Pariwisata",
    pengampu: "Dinas Pariwisata",
    noTelp: "086868130487",
    kecamatan: "Samigaluh",
    alamat: "RT 84 RW 85, Samiran, Samigaluh",
  },
  {
    index: 88,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Industri Berkah",
    skala: "Usaha Kecil",
    badanHukum: "Firma",
    bidang: "Industri Manufaktur",
    pengampu: "Dinas Koperasi dan UKM",
    noTelp: "086868130488",
    kecamatan: "Temon",
    alamat: "RT 85 RW 86, Temon Timur, Temon",
  },
  {
    index: 89,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Pendidikan Bahagia",
    skala: "Usaha Mikro",
    badanHukum: "Perseorangan",
    bidang: "Pendidikan",
    pengampu: "Dinas Sosial",
    noTelp: "086868130489",
    kecamatan: "Wates",
    alamat: "RT 86 RW 87, Wetan, Wates",
    position: [-7.871374, 110.148815],
  },
  {
    index: 90,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Kesehatan Terdepan",
    skala: "Usaha Menengah",
    badanHukum: "CV",
    bidang: "Kesehatan",
    pengampu: "Dinas Sosial",
    noTelp: "086868130490",
    kecamatan: "Sentolo",
    alamat: "RT 87 RW 88, Senayan, Sentolo",
  },
  {
    index: 91,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Transportasi Maju",
    skala: "Usaha Kecil",
    badanHukum: "Firma",
    bidang: "Transportasi dan Logistik",
    pengampu: "Dinas Perhubungan",
    noTelp: "086868130491",
    kecamatan: "Pengasih",
    alamat: "RT 88 RW 89, Pengasih Utara, Pengasih",
  },
  {
    index: 92,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Pertanian Bahagia",
    skala: "Usaha Mikro",
    badanHukum: "Perseorangan",
    bidang: "Pertanian",
    pengampu: "Dinas Pertanian dan Pangan",
    noTelp: "086868130492",
    kecamatan: "Nanggulan",
    alamat: "RT 89 RW 90, Sidoarum, Nanggulan",
  },
  {
    index: 93,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Hukum Berkah",
    skala: "Usaha Menengah",
    badanHukum: "PT",
    bidang: "Hukum dan Konsultasi",
    pengampu: "Dinas PMD Dalduk",
    noTelp: "086868130493",
    kecamatan: "Samigaluh",
    alamat: "RT 90 RW 91, Samiran, Samigaluh",
  },
  {
    index: 94,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Properti Sejahtera",
    skala: "Usaha Kecil",
    badanHukum: "Firma",
    bidang: "Properti dan Real Estat",
    pengampu: "Dinas Pariwisata",
    noTelp: "086868130494",
    kecamatan: "Temon",
    alamat: "RT 91 RW 92, Temon Timur, Temon",
  },
  {
    index: 95,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Konsultasi Bahagia",
    skala: "Usaha Mikro",
    badanHukum: "Perseorangan",
    bidang: "Hukum dan Konsultasi",
    pengampu: "Dinas PMD Dalduk",
    noTelp: "086868130495",
    kecamatan: "Wates",
    alamat: "RT 92 RW 93, Wetan, Wates",
    position: [-7.85573, 110.152935],
  },
  {
    index: 96,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Tambang Mandiri",
    skala: "Usaha Menengah",
    badanHukum: "CV",
    bidang: "Pertambangan",
    pengampu: "Dinas Lingkungan Hidup",
    noTelp: "086868130496",
    kecamatan: "Sentolo",
    alamat: "RT 93 RW 94, Senayan, Sentolo",
  },
  {
    index: 97,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Laut Mandiri",
    skala: "Usaha Kecil",
    badanHukum: "Firma",
    bidang: "Perikanan",
    pengampu: "Dinas Kelautan dan Perikanan",
    noTelp: "086868130497",
    kecamatan: "Pengasih",
    alamat: "RT 94 RW 95, Pengasih Timur, Pengasih",
  },
  {
    index: 98,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Pariwisata Maju",
    skala: "Usaha Mikro",
    badanHukum: "Perseorangan",
    bidang: "Pariwisata",
    pengampu: "Dinas Pariwisata",
    noTelp: "086868130498",
    kecamatan: "Nanggulan",
    alamat: "RT 95 RW 96, Sidoarum, Nanggulan",
  },
  {
    index: 99,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Industri Mandiri",
    skala: "Usaha Menengah",
    badanHukum: "PT",
    bidang: "Industri Manufaktur",
    pengampu: "Dinas Koperasi dan UKM",
    noTelp: "086868130499",
    kecamatan: "Samigaluh",
    alamat: "RT 96 RW 97, Samiran, Samigaluh",
  },
  {
    index: 100,
    avatar: "/logo-umkm/logo-umkm-1.png",
    name: "Pendidikan Sehat",
    skala: "Usaha Kecil",
    badanHukum: "Firma",
    bidang: "Pendidikan",
    pengampu: "Dinas Sosial",
    noTelp: "086868130500",
    kecamatan: "Temon",
    alamat: "RT 97 RW 98, Temon Barat, Temon",
  },
];
